name: DataPipeline

on:
  workflow_dispatch: 
  schedule:
    - cron:  '0 10 * * *'

jobs:
  scrape_pdf:
    runs-on: ubuntu-latest
    env:
      PDF_SOURCE: 'http://stopcoronavirus.mcgm.gov.in/assets/docs/Dashboard.pdf'
      PDF_FILE_PATH: '/tmp/stopcovid-dashboard'

    steps:
      - name: Set env
        run: echo ::set-env name=PDF_FILE_PATH::$(echo $PDF_FILE_PATH-$(date +%s).pdf)
      - name: Check out this repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
      - name: Download and scrap data from PDF dashboard file.
        run: |
          python -m pdf_scrapper download-pdf --dashboard-pdf-url $PDF_SOURCE --output $PDF_FILE_PATH
      - uses: actions/upload-artifact@v2
        with:
          name: pdf
          path: ${{ env.PDF_FILE_PATH }}